spring.application.name=Premier League

server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGO_URI}

# Swagger configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Properties for custom log format
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %class{36} - %X{uuId} - %M:%L - %msg%n